### ISSUE TITLE
NewRugArchiveProject: fails with "com/atomist/rug/kind/dynamic/DefaultViewFinder$"

### ISSUE THREAD

**Issue by mmoayyed** [atomist/rug-cli#111] opened 2017-02-16 11:22 UTC
Running on Windows 10 with:

```
rug 0.22.0
https://github.com/atomist/rug-cli.git (git revision 001b2ea; last commit 2017-02-02)
```

I installed rug via choco and have been trying to go through the docs. When attempting to generate a new rug archive:

```
rug generate atomist-rugs:rug-archive:NewRugArchiveProject \     my-rug-project \     group_id=atomist-rugs \     version=0.1.0 \     description="My first Rug project"
```

I see:

```
Processing dependencies
  Downloading atomist-rugs/rug-archive/maven-metadata.xml < rugs (737 bytes) succeeded
  Downloading com/atomist/rug/maven-metadata.xml < rug-types (1008 bytes) succeeded
Resolving dependencies for atomist-rugs:rug-archive:latest completed
Loading atomist-rugs:rug-archive:0.11.0 into runtime failed

com/atomist/rug/kind/dynamic/DefaultViewFinder$
```

From: http://docs.atomist.com/rug/rug-lifecycle/

**Comment by Lawouach** [comment] 2017-02-16 15:00
I can confirm I have the same behavior.

**Comment by Lawouach** [comment] 2017-02-16 15:01
Here is the tree of dependencies:

```
$ rug generate -ur atomist-rugs:rug-archive:NewRugArchiveProject \     my-rug-project \     group_id=atomist-rugs \     version=0.1.0 \     description="My first Rug project"
Processing dependencies
  Downloading atomist-rugs/rug-archive/maven-metadata.xml < rugs (737 bytes) succeeded
  Downloading com/atomist/rug/maven-metadata.xml < rug-types (1008 bytes) succeeded
Dependency report for atomist-rugs:rug-archive:latest
  atomist-rugs:rug-archive:zip:0.11.0 [compile]
  +- com.atomist:rug:jar:0.12.0 [compile]
  |  +- com.atomist:artifact-source:jar:0.14.4 [compile]
  |  |  +- commons-io:commons-io:jar:2.5 [compile]
  |  |  +- org.apache.commons:commons-compress:jar:1.12 [compile]
  |  |  \- org.scala-lang:scala-library:jar:2.11.8 [compile]
  |  +- com.atomist:rug-compiler:jar:0.6.0 [compile]
  |  +- com.atomist:rug-typescript-compiler:jar:0.11.0 [compile]
  |  |  +- commons-codec:commons-codec:jar:1.10 [compile]
  |  |  \- com.eclipsesource.j2v8:j2v8_win32_x86_64:jar:4.6.0 [compile]
  |  +- com.coveo:nashorn-commonjs-modules:jar:1.0.6 [compile]
  |  +- com.github.julianthome:inmemantlr-api:jar:1.3.2 [compile]
  |  |  +- org.antlr:antlr4:jar:4.6 [compile]
  |  |  |  +- org.antlr:antlr4-runtime:jar:4.6 [compile]
  |  |  |  +- org.antlr:antlr-runtime:jar:3.5.2 [compile]
  |  |  |  +- org.antlr:ST4:jar:4.0.8 [compile]
  |  |  |  +- org.abego.treelayout:org.abego.treelayout.core:jar:1.0.3 [compile]
  |  |  |  \- org.glassfish:javax.json:jar:1.0.4 [compile]
  |  |  \- org.eclipse.jdt.core.compiler:ecj:jar:4.6.1 [compile]
  |  +- com.github.javaparser:javaparser-core:jar:2.5.1 [compile]
  |  +- org.scalameta:scalameta_2.11:jar:1.4.0 [compile]
  |  |  +- org.scalameta:common_2.11:jar:1.4.0 [compile]
  |  |  +- org.scalameta:dialects_2.11:jar:1.4.0 [compile]
  |  |  +- org.scalameta:parsers_2.11:jar:1.4.0 [compile]
  |  |  |  +- org.scalameta:inputs_2.11:jar:1.4.0 [compile]
  |  |  |  \- org.scalameta:tokens_2.11:jar:1.4.0 [compile]
  |  |  +- org.scalameta:quasiquotes_2.11:jar:1.4.0 [compile]
  |  |  +- org.scalameta:tokenizers_2.11:jar:1.4.0 [compile]
  |  |  |  \- com.lihaoyi:scalaparse_2.11:jar:0.4.2 [compile]
  |  |  |     +- com.lihaoyi:fastparse_2.11:jar:0.4.2 [compile]
  |  |  |     |  \- com.lihaoyi:fastparse-utils_2.11:jar:0.4.2 [compile]
  |  |  |     \- com.lihaoyi:sourcecode_2.11:jar:0.1.3 [compile]
  |  |  +- org.scalameta:transversers_2.11:jar:1.4.0 [compile]
  |  |  +- org.scalameta:trees_2.11:jar:1.4.0 [compile]
  |  |  \- org.scalameta:inline_2.11:jar:1.4.0 [compile]
  |  +- com.github.spullara.mustache.java:compiler:jar:0.9.3 [compile]
  |  +- org.apache.velocity:velocity:jar:1.7 [compile]
  |  |  +- commons-collections:commons-collections:jar:3.2.1 [compile]
  |  |  \- commons-lang:commons-lang:jar:2.4 [compile]
  |  +- org.apache.httpcomponents:httpclient:jar:4.5.2 [compile]
  |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.4 [compile]
  |  +- org.apache.commons:commons-lang3:jar:3.5 [compile]
  |  +- org.springframework:spring-web:jar:4.3.5.RELEASE [compile]
  |  |  +- org.springframework:spring-aop:jar:4.3.5.RELEASE [compile]
  |  |  +- org.springframework:spring-beans:jar:4.3.5.RELEASE [compile]
  |  |  +- org.springframework:spring-context:jar:4.3.5.RELEASE [compile]
  |  |  |  \- org.springframework:spring-expression:jar:4.3.5.RELEASE [compile]
  |  |  \- org.springframework:spring-core:jar:4.3.5.RELEASE [compile]
  |  +- org.scala-lang.modules:scala-parser-combinators_2.11:jar:1.0.4 [compile]
  |  +- com.typesafe.scala-logging:scala-logging_2.11:jar:3.5.0 [compile]
  |  |  \- org.scala-lang:scala-reflect:jar:2.11.8 [compile]
  |  +- org.slf4j:slf4j-api:jar:1.7.22 [compile]
  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.22 [compile]
  |  +- ch.qos.logback:logback-classic:jar:1.1.8 [compile]
  |  |  \- ch.qos.logback:logback-core:jar:1.1.8 [compile]
  |  +- ch.qos.logback:logback-access:jar:1.1.8 [compile]
  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.8.6 [compile]
  |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.8.6 [compile]
  |  |  \- org.yaml:snakeyaml:jar:1.17 [compile]
  |  +- com.fasterxml.jackson.module:jackson-module-scala_2.11:jar:2.8.6 [compile]
  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.6 [compile]
  |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.6 [compile]
  |  |  \- com.fasterxml.jackson.module:jackson-module-paranamer:jar:2.8.6 [compile]
  |  |     \- com.thoughtworks.paranamer:paranamer:jar:2.8 [compile]
  |  \- com.github.mifmif:generex:jar:1.0.2 [compile]
  |     \- dk.brics.automaton:automaton:jar:1.11-8 [compile]
  \- atomist-rugs:common-editors:zip:0.6.0 [compile]
Resolving dependencies for atomist-rugs:rug-archive:latest completed

com/atomist/rug/kind/dynamic/ViewFinder
```

I'm also running rug-0.22.0 (fresh install)

**Comment by Lawouach** [comment] 2017-02-16 15:09
I think it's due to the range of rug runtime version the Rug archive says it supports [here ](https://github.com/atomist-rugs/rug-archive/blob/master/.atomist/manifest.yml) `requires: "[0.11.0,1.0.0)"`. Rug 0.12.0 was released with breaking changes and the CLI 0.22.0 chokes on them it seems.

As a workaround, would you be able to upgrade to the latest CLI? (0.23.0) which did work here.

**Comment by mmoayyed** [comment] 2017-02-17 13:00
Sure. WIP.

by the way it would be tremendously easier if I could just: `rug upgrade` rather than `choco upgrade rug-cli -s "'https://atomist.jfrog.io/atomist/api/nuget/nuget'"`

**Comment by mmoayyed** [comment] 2017-02-17 13:04
I can confirm that 0.23.0 solves the issue.

```
rug generate atomist-rugs:rug-archive:NewRugArchiveProject my-rug-project group_id=atomist-rugs version=0.1.0 description="My first Rug project" Resolving dependencies for atomist-rugs:rug-archive:latest completed
Loading atomist-rugs:rug-archive:0.11.0 into runtime completed
Running generator NewRugArchiveProject of atomist-rugs:rug-archive:0.11.0 completed

> Project
  C:\Misagh\Clients\tmp\my-rug-project (6 kb in 6 files)

> Changes
  +- .atomist
  |  +- editors
  |  |  \- AddReadme.rug
  |  +- manifest.yml
  |  \- tests
  |     \- AddReadme.rt
  +- .atomist.yml
  +- .gitignore
  \- README.md

Successfully generated new project my-rug-project
```

Thank you.

**Closed** 2017-02-17 13:05 UTC
Labels: question
